version = 0.1

[default.deploy.parameters]
stack_name = "gestor-stock-ventas-prod"
resolve_s3 = true
s3_prefix = "gestor-stock-ventas-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "CommerceStage=\"prod\" RetentionDays=\"90\" FrontendBaseUrl=\"https://comercios.gestionystock.com/\" BillingMonthlyAmount=\"35000\" BillingCurrencyId=\"ARS\" BillingTrialDays=\"30\" BillingGraceDays=\"3\" BillingPlanReason=\"G&S Comercios\" BillingPublicRegistrationPath=\"/estado-cuenta\" MercadoPagoAccessToken=\"APP_USR-6135434379834665-081014-4b9e30ab9228b1d565b84ce1eaa02304-134472590\" MercadoPagoWebhookSecret=\"ab97d8221873a954c49e3537e22096b7e61d0e308c9e7c4bf5f024d349c9ec64\" MercadoPagoPreapprovalPlanId=\"648371d03d8f475b8dfde3b9a3f7a61a\" MercadoPagoReactivationPlanId=\"1e7b141216d24d9eaeb1734e32f82522\""
image_repositories = []
