version = 0.1

[default.deploy.parameters]
stack_name = "gestor-stock-ventas-prod"
resolve_s3 = true
s3_prefix = "gestor-stock-ventas-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "CommerceStage=\"prod\" RetentionDays=\"90\" FrontendBaseUrl=\"https://comercios.gestionystock.com/\" BillingMonthlyAmount=\"42000\" BillingCurrencyId=\"ARS\" BillingTrialDays=\"30\" BillingGraceDays=\"3\" BillingPlanReason=\"G&S Comercios\" BillingPublicRegistrationPath=\"/suscripcion\" MercadoPagoPreapprovalPlanId=\"\" MercadoPagoReactivationPlanId=\"\""
image_repositories = []
